{% set name = "sentinel-timelapse" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ..

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - sentinel-timelapse = sentinel_timelapse.cli:main

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
    - wheel
  run:
    - python >=3.8
    - geopandas >=0.12.0
    - shapely >=1.8.0
    - rasterio >=1.3.0
    - pyproj >=3.4.0
    - numpy >=1.21.0
    - requests >=2.28.0



test:
  imports:
    - sentinel_timelapse
    - sentinel_timelapse.geometry
    - sentinel_timelapse.stac
    - sentinel_timelapse.processing
    - sentinel_timelapse.main
    - sentinel_timelapse.cli
  commands:
    - pip install pystac-client>=0.7.0 planetary-computer>=0.5.0
    - pip check
    - sentinel-timelapse --help

about:
  home: https://github.com/ramaguirre/sentinel_timelapse
  license: MIT
  license_family: MIT
  summary: A Python package for downloading and processing Sentinel satellite imagery for timelapse creation
  doc_url: https://sentinel-timelapse.readthedocs.io/
  dev_url: https://github.com/ramaguirre/sentinel_timelapse

extra:
  recipe-maintainers:
    - ramaguirre
